"""
Auto-Cronfig v3 — VibeScan Engine
Targets NEW repos created by AI vibe-coding tools (Lovable, Replit, Base44,
Bolt, v0, Cursor, Windsurf, Copilot Workspace, etc.) pushed in the last 24h–7d.
These repos have the highest rate of live leaked secrets because:
  - Developers paste API keys directly into AI prompts
  - AI tools scaffold .env files with real credentials
  - Developers push without reviewing AI-generated code
  - No secret-scanning experience in new vibe-coders
"""

import re
import sys
import time
import base64
import logging
import datetime
from typing import List, Optional, Callable, Dict
from concurrent.futures import ThreadPoolExecutor, as_completed

logger = logging.getLogger(__name__)

from .scanner import RawFinding, _make_headers, _request_with_backoff, _scan_text_for_patterns

try:
    from tqdm import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False

# ── Vibe-coded platform signatures ───────────────────────────────────────────
# These strings appear in README, package.json, or root files of AI-scaffolded repos

VIBE_PLATFORM_SIGNALS = {
    "lovable": [
        "lovable.dev", "lovable-tagger", "lovable-uploads",
        "This project was created with Lovable",
        "supabase", "lovable.app",
    ],
    "bolt": [
        "bolt.new", "stackblitz", "webcontainer",
        "This project was bootstrapped with Bolt",
        "bolt-vite", "bolt-nextjs",
    ],
    "replit": [
        "repl.it", "replit.com", "replit-nix",
        ".replit", "replit.nix", "REPL_ID",
        "This was created on Replit",
    ],
    "base44": [
        "base44.com", "base44-app", "base44_app",
        "Created with Base44", "base44.io",
    ],
    "v0": [
        "v0.dev", "v0 by Vercel", "Generated by v0",
        "This component was generated",
    ],
    "cursor": [
        ".cursorrules", "cursor.sh", "Cursor AI",
        "This code was written with Cursor",
    ],
    "windsurf": [
        "codeium.com", "windsurf", ".windsurfrules",
        "Windsurf Editor",
    ],
    "claude": [
        "claude.ai", "anthropic", "Built with Claude",
        "Generated by Claude", "claude-3",
    ],
    "copilot": [
        "GitHub Copilot", "copilot-workspace",
        "copilot generated", "gh-copilot",
    ],
    "devin": [
        "devin.ai", "Devin AI", "Created by Devin",
    ],
    "gptengineer": [
        "gptengineer.app", "gpt-engineer",
        "Generated by GPT Engineer",
    ],
    "magic": [
        "magic.dev", "Magic AI",
    ],
    "vercel_ai": [
        "vercel/ai", "ai-sdk", "@ai-sdk/",
        "useChat", "streamText", "generateText",
    ],
    "supabase_scaffold": [
        "supabase/supabase-js", "createClient",
        "SUPABASE_URL", "SUPABASE_ANON_KEY",
    ],
    "firebase_scaffold": [
        "firebase/app", "initializeApp",
        "FIREBASE_API_KEY", "firebaseConfig",
    ],
}

# ── GitHub code search queries targeting vibe-coded new repos ────────────────
# Each query uses: vibe tool signal + secret pattern + sort:indexed (newest first)

VIBE_SCAN_QUERIES = [

    # ── Lovable + secrets ────────────────────────────────────────────────────
    "lovable-tagger SUPABASE_SERVICE_ROLE_KEY",
    "lovable-tagger OPENAI_API_KEY",
    "lovable.dev filename:.env",
    "lovable-tagger filename:.env",
    "lovable-uploads STRIPE_SECRET_KEY",
    "lovable.app API_KEY filename:.env",
    "supabase lovable OPENAI_API_KEY filename:.env",
    "supabase lovable ANTHROPIC_API_KEY",
    "lovable-tagger sk-ant-api",
    "lovable-tagger ghp_",

    # ── Bolt.new + secrets ───────────────────────────────────────────────────
    "bolt.new filename:.env OPENAI_API_KEY",
    "stackblitz webcontainer filename:.env",
    "bolt-vite STRIPE_SECRET_KEY",
    "bolt.new API_KEY filename:.env",
    "bolt.new SUPABASE_SERVICE_ROLE_KEY",
    "bolt.new sk-ant-api",
    "bolt.new DATABASE_URL filename:.env",

    # ── Replit + secrets ─────────────────────────────────────────────────────
    "replit.nix OPENAI_API_KEY",
    "replit.com filename:.env STRIPE_SECRET_KEY",
    ".replit filename:.env API_KEY",
    "REPL_ID OPENAI_API_KEY",
    "replit ANTHROPIC_API_KEY filename:.env",
    "replit SUPABASE_SERVICE_ROLE_KEY",
    "replit DATABASE_URL filename:.env",
    "replit TWILIO_AUTH_TOKEN",
    "replit SENDGRID_API_KEY",

    # ── Base44 + secrets ─────────────────────────────────────────────────────
    "base44.com filename:.env",
    "base44 OPENAI_API_KEY filename:.env",
    "base44 STRIPE_SECRET_KEY",
    "base44 SUPABASE_SERVICE_ROLE_KEY",
    "base44 API_KEY filename:.env",

    # ── v0 by Vercel + secrets ───────────────────────────────────────────────
    "v0.dev OPENAI_API_KEY filename:.env",
    "v0.dev STRIPE_SECRET_KEY",
    "Generated by v0 filename:.env",
    "v0.dev SUPABASE_SERVICE_ROLE_KEY",
    "v0.dev DATABASE_URL filename:.env",

    # ── Cursor + secrets ─────────────────────────────────────────────────────
    ".cursorrules filename:.env OPENAI_API_KEY",
    ".cursorrules STRIPE_SECRET_KEY",
    ".cursorrules ANTHROPIC_API_KEY",
    ".cursorrules API_KEY filename:.env",
    "cursorrules SUPABASE_SERVICE_ROLE_KEY",

    # ── Windsurf + secrets ───────────────────────────────────────────────────
    ".windsurfrules filename:.env API_KEY",
    ".windsurfrules OPENAI_API_KEY",
    ".windsurfrules STRIPE_SECRET_KEY",

    # ── Claude-generated + secrets ───────────────────────────────────────────
    "claude.ai filename:.env OPENAI_API_KEY",
    "Generated by Claude STRIPE_SECRET_KEY",
    "anthropic filename:.env DATABASE_URL",

    # ── Generic AI app scaffolding patterns ──────────────────────────────────
    # New Supabase + secrets (most vibe apps use Supabase)
    "supabase createClient SUPABASE_SERVICE_ROLE_KEY filename:.env",
    "supabase createClient OPENAI_API_KEY filename:.env",
    "SUPABASE_URL SUPABASE_SERVICE_ROLE_KEY filename:.env",
    "NEXT_PUBLIC_SUPABASE_URL SUPABASE_SERVICE_ROLE_KEY",
    "supabase STRIPE_SECRET_KEY filename:.env",
    "supabase OPENAI_API_KEY language:typescript",
    "supabase sk-ant-api filename:.env",

    # New Firebase + secrets
    "firebaseConfig OPENAI_API_KEY filename:.env",
    "initializeApp apiKey filename:.env",
    "FIREBASE_API_KEY OPENAI_API_KEY filename:.env",

    # Vercel AI SDK + secrets (used in almost all vibe apps)
    "@ai-sdk OPENAI_API_KEY filename:.env",
    "ai-sdk ANTHROPIC_API_KEY filename:.env",
    "useChat OPENAI_API_KEY filename:.env",
    "streamText OPENAI_API_KEY filename:.env",
    "generateText ANTHROPIC_API_KEY filename:.env",

    # Next.js + Tailwind (most vibe app template)
    "next.config OPENAI_API_KEY filename:.env.local",
    "NEXTAUTH_SECRET filename:.env.local",
    "NEXTAUTH_URL OPENAI_API_KEY filename:.env.local",
    "next.config STRIPE_SECRET_KEY",
    "NEXT_PUBLIC_ STRIPE_SECRET_KEY filename:.env",
    "NEXT_PUBLIC_ DATABASE_URL filename:.env.local",

    # React + Vite (second most common vibe template)
    "vite.config OPENAI_API_KEY filename:.env",
    "vite VITE_SUPABASE_ANON_KEY filename:.env",
    "vite VITE_STRIPE_PUBLIC_KEY filename:.env",

    # Prisma + secrets (DB ORM in most vibe apps)
    "prisma DATABASE_URL filename:.env",
    "schema.prisma DATABASE_URL filename:.env",
    "prisma OPENAI_API_KEY filename:.env",

    # Drizzle ORM (newer vibe apps)
    "drizzle DATABASE_URL filename:.env",
    "drizzle OPENAI_API_KEY filename:.env",

    # New .env.local leaks (Vercel/Next convention)
    "OPENAI_API_KEY filename:.env.local",
    "ANTHROPIC_API_KEY filename:.env.local",
    "STRIPE_SECRET_KEY filename:.env.local",
    "DATABASE_URL filename:.env.local",
    "SUPABASE_SERVICE_ROLE_KEY filename:.env.local",
    "GITHUB_TOKEN filename:.env.local",
    "RESEND_API_KEY filename:.env.local",
    "SENDGRID_API_KEY filename:.env.local",

    # Common new-dev mistakes
    "sk-proj- filename:.env",           # New OpenAI project keys
    "sk-proj- language:python",
    "sk-proj- language:typescript",
    "sk-proj- filename:.env.local",
    "OPENAI_API_KEY= filename:.env",
    "ANTHROPIC_API_KEY= filename:.env",
    "RESEND_API_KEY filename:.env",     # Resend (popular new email API)
    "UPSTASH_REDIS_REST_TOKEN filename:.env",  # Upstash (popular in vibe apps)
    "CLERK_SECRET_KEY filename:.env",   # Clerk auth
    "CLERK_PUBLISHABLE_KEY filename:.env",
    "PINECONE_API_KEY filename:.env",   # Pinecone (vector DB)
    "QDRANT_API_KEY filename:.env",
    "WEAVIATE_API_KEY filename:.env",

    # Expo / React Native (mobile vibe apps)
    "expo OPENAI_API_KEY filename:.env",
    "expo-router STRIPE_SECRET_KEY",

    # Specific leaked patterns seen in vibe apps
    "process.env.OPENAI_API_KEY language:typescript",
    "process.env.ANTHROPIC_API_KEY language:typescript",
    "process.env.STRIPE_SECRET_KEY language:typescript",
    "import.meta.env.VITE_OPENAI language:typescript",
]

# ── Date-filtered repo search ─────────────────────────────────────────────────

def _days_ago(n: int) -> str:
    """Return ISO date string N days ago (YYYY-MM-DD)."""
    d = datetime.datetime.utcnow() - datetime.timedelta(days=n)
    return d.strftime("%Y-%m-%d")


class VibeScanner:
    """
    Scans new AI-scaffolded repositories for leaked secrets.
    Prioritises repos pushed/updated in the last 24h → 7d → 30d.
    """

    BASE = "https://api.github.com"

    def __init__(self, token: Optional[str] = None, workers: int = 6, memory=None):
        self.token   = token
        self.workers = workers
        self.memory  = memory
        self._headers = _make_headers(token)
        self._seen: set = set()

    # ── Search new repos by platform signal + secret ──────────────────────────
    def _code_search(
        self,
        query: str,
        max_results: int = 20,
        callback: Optional[Callable] = None,
    ) -> List[RawFinding]:
        """Run a GitHub code search, fetch file contents, scan for patterns."""
        findings: List[RawFinding] = []

        resp = _request_with_backoff(
            "GET", f"{self.BASE}/search/code",
            self._headers,
            params={"q": query, "per_page": min(30, max_results),
                    "sort": "indexed", "order": "desc"},
        )
        if not resp or resp.status_code != 200:
            if resp and resp.status_code == 422:
                pass  # query too short
            elif resp and resp.status_code == 403:
                time.sleep(20)
            return findings

        for item in resp.json().get("items", [])[:max_results]:
            repo_full = item["repository"]["full_name"]
            file_path = item["path"]
            html_url  = item.get("html_url",
                f"https://github.com/{repo_full}/blob/HEAD/{file_path}")

            # Check repo age — skip repos older than 90 days
            pushed = item["repository"].get("pushed_at", "")
            if pushed:
                try:
                    age = (datetime.datetime.utcnow() -
                           datetime.datetime.strptime(pushed[:10], "%Y-%m-%d")).days
                    if age > 90:
                        continue
                except Exception as exc:
                    logger.debug("date parse error: %s", exc)

            cr = _request_with_backoff("GET",
                item.get("url", f"{self.BASE}/repos/{repo_full}/contents/{file_path}"),
                self._headers)
            if not cr or cr.status_code != 200:
                continue

            raw_b64 = cr.json().get("content", "")
            if not raw_b64:
                continue
            try:
                content = base64.b64decode(raw_b64).decode("utf-8", errors="replace")
                hits = _scan_text_for_patterns(
                    content, repo_full, file_path, html_url, memory=self.memory)
                for hit in hits:
                    key = (hit.repo, hit.file_path, hit.pattern_name, hit.match_preview)
                    if key not in self._seen:
                        self._seen.add(key)
                        findings.append(hit)
                        if callback:
                            try:
                                callback(hit)
                            except Exception as exc:
                                logger.debug("callback error: %s", exc)
            except Exception as exc:
                logger.debug("decode error: %s", exc)

            time.sleep(6)  # GitHub code search rate limit

        return findings

    # ── Repo search — find new AI-scaffolded repos directly ──────────────────
    def search_new_vibe_repos(
        self,
        days: int = 7,
        max_repos: int = 100,
        callback: Optional[Callable] = None,
    ) -> List[RawFinding]:
        """
        Search GitHub repo API for repos created/pushed recently
        that match vibe-coded tool signatures. Then scan their files.
        """
        since = _days_ago(days)
        all_findings: List[RawFinding] = []

        repo_queries = [
            f"lovable-tagger pushed:>{since}",
            f"bolt.new in:readme pushed:>{since}",
            f"topic:replit pushed:>{since}",
            f"lovable.dev in:readme pushed:>{since}",
            f"supabase nextjs pushed:>{since} stars:0..5",
            f"vite react supabase pushed:>{since} stars:0..3",
            f"nextjs prisma openai pushed:>{since} stars:0..5",
            f"expo react-native supabase pushed:>{since} stars:0..3",
            f".cursorrules in:path pushed:>{since}",
            f".windsurfrules in:path pushed:>{since}",
            f"base44 in:readme pushed:>{since}",
            f"v0.dev in:readme pushed:>{since}",
        ]

        found_repos: list = []
        for rq in repo_queries:
            resp = _request_with_backoff(
                "GET", f"{self.BASE}/search/repositories",
                self._headers,
                params={"q": rq, "sort": "updated", "order": "desc",
                        "per_page": 20},
            )
            if not resp or resp.status_code != 200:
                continue
            items = resp.json().get("items", [])
            for r in items:
                rname = r["full_name"]
                if rname not in [x["full_name"] for x in found_repos]:
                    found_repos.append(r)
            time.sleep(3)

        print(f"\n  Found {len(found_repos)} vibe-coded repos — scanning…\n")

        for repo in found_repos[:max_repos]:
            rname = repo["full_name"]
            owner, rn = rname.split("/", 1)
            try:
                from .scanner import RepoScanner
                rs = RepoScanner(token=self.token, workers=self.workers,
                                 memory=self.memory)
                hits = rs.scan_repo(owner, rn)
                for hit in hits:
                    key = (hit.repo, hit.file_path, hit.pattern_name, hit.match_preview)
                    if key not in self._seen:
                        self._seen.add(key)
                        all_findings.append(hit)
                        if callback:
                            try:
                                callback(hit)
                            except Exception as exc:
                                logger.debug("callback error: %s", exc)
            except Exception as exc:
                logger.debug("repo scan error for %s: %s", rname, exc)

        return all_findings

    # ── Run all vibe queries (code search) ────────────────────────────────────
    def run_vibe_queries(
        self,
        max_per_query: int = 20,
        callback: Optional[Callable] = None,
        fast: bool = True,
    ) -> List[RawFinding]:
        """
        Run all VIBE_SCAN_QUERIES targeting AI-scaffolded repos.
        fast=True: parallel batches of 3.
        """
        self._seen = set()
        all_findings: List[RawFinding] = []
        queries = list(VIBE_SCAN_QUERIES)
        total   = len(queries)

        if fast:
            batch_size = 3
            batches = [queries[i:i+batch_size] for i in range(0, total, batch_size)]
            done = 0
            for batch in batches:
                with ThreadPoolExecutor(max_workers=batch_size) as ex:
                    futs = {ex.submit(self._code_search, q, max_per_query, callback): q
                            for q in batch}
                    for fut in as_completed(futs):
                        try:
                            hits = fut.result()
                            all_findings.extend(hits)
                            done += 1
                            pct = int(done / total * 100)
                            bar = "█" * (pct // 5) + "░" * (20 - pct // 5)
                            sys.stdout.write(
                                f"\r  [{bar}] {pct:3d}%  "
                                f"{done}/{total} queries  "
                                f"{C.RED if any(h.severity=='CRITICAL' for h in all_findings) else ''}"
                                f"{len(all_findings)} found  \033[0m"
                            )
                            sys.stdout.flush()
                        except Exception as exc:
                            logger.debug("batch error: %s", exc)
                time.sleep(2)
        else:
            it = tqdm(queries, desc="  VibeScan", unit="q") if HAS_TQDM else queries
            for q in it:
                try:
                    hits = self._code_search(q, max_per_query, callback)
                    all_findings.extend(hits)
                except KeyboardInterrupt:
                    print("\n  Interrupted.")
                    break
                except Exception as exc:
                    logger.debug("query error: %s", exc)

        print()
        return all_findings

    # ── Platform-specific scan ─────────────────────────────────────────────────
    def scan_platform(
        self,
        platform: str,
        max_per_query: int = 20,
        callback: Optional[Callable] = None,
    ) -> List[RawFinding]:
        """Scan only queries for a specific vibe platform."""
        self._seen = set()
        platform_lower = platform.lower()
        matching = [q for q in VIBE_SCAN_QUERIES
                    if platform_lower in q.lower()]
        if not matching:
            logger.warning("No queries for platform: %s", platform)
            return []

        all_findings: List[RawFinding] = []
        print(f"\n  Platform: {platform}  ({len(matching)} queries)\n")
        for i, q in enumerate(matching, 1):
            pct = int(i / len(matching) * 100)
            bar = "█" * (pct // 5) + "░" * (20 - pct // 5)
            sys.stdout.write(f"\r  [{bar}] {pct:3d}%  {i}/{len(matching)}  "
                             f"{len(all_findings)} found  ")
            sys.stdout.flush()
            hits = self._code_search(q, max_per_query, callback)
            all_findings.extend(hits)
        print()
        return all_findings

    # ── Continuous vibe scan ──────────────────────────────────────────────────
    def run_continuous(
        self,
        interval_seconds: int = 1800,
        output_path: Optional[str] = None,
    ):
        """Scan new vibe repos every interval_seconds. Loops until Ctrl+C."""
        import json as _json
        n = 0
        print(f"  VibeScan continuous mode — every {interval_seconds}s\n  Ctrl+C to stop\n")
        while True:
            n += 1
            ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
            print(f"\n  ── VibeScan #{n}  {ts}")
            t0 = time.monotonic()
            findings = self.run_vibe_queries(max_per_query=20, fast=True)
            dur = time.monotonic() - t0
            crit = sum(1 for f in findings if f.severity == "CRITICAL")
            high = sum(1 for f in findings if f.severity == "HIGH")
            print(f"  ✓ {len(findings)} findings in {dur:.0f}s  "
                  f"\033[91mCRIT:{crit}\033[0m  \033[93mHIGH:{high}\033[0m")
            if output_path and findings:
                try:
                    existing: list = []
                    try:
                        with open(output_path) as f:
                            existing = _json.load(f)
                    except Exception as exc:
                        logger.debug("load error: %s", exc)
                    for h in findings:
                        existing.append({
                            "scan": n, "ts": ts, "repo": h.repo,
                            "file": h.file_path, "pattern": h.pattern_name,
                            "severity": h.severity, "preview": h.match_preview,
                            "url": h.url,
                        })
                    with open(output_path, "w") as f:
                        _json.dump(existing, f, indent=2)
                    print(f"  → saved to {output_path}")
                except Exception as exc:
                    logger.warning("save error: %s", exc)
            print(f"  Next scan in {interval_seconds}s…")
            try:
                for rem in range(interval_seconds, 0, -1):
                    sys.stdout.write(f"\r  ⏱  {rem:5d}s  ")
                    sys.stdout.flush()
                    time.sleep(1)
                print("\r" + " " * 20)
            except KeyboardInterrupt:
                print("\n  Stopped.")
                break


# colour alias safe for non-tty
try:
    from colorama import Fore as C
except ImportError:
    class C:  # type: ignore
        RED = YELLOW = GREEN = CYAN = ""
